services:
  django:
    build:
      context: ./back
    restart: unless-stopped
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./back:/app
    depends_on:
      - db
  nuxt:
    build:
      context: ./front
    container_name: TempestBoard-front
    restart: unless-stopped
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - django
  db:
    image: postgres:16-alpine
    command: postgres -c config_file=/etc/postgresql.conf
    shm_size: '4gb'
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    ports:
      - "6932:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql.conf
      - ./data/postgresql:/var/lib/postgresql/data
      - ./docker/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'tempestboard'
      ALLOW_IP_RANGE: 0.0.0.0/0
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
      retries: 300
