services:

  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy-proxy
    ports:
      - "80:80"  # HTTP
      - "443:443" # HTTPS (if needed later)
      - "8404:8404" # Stats page
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network


  db:
    image: postgres:16-alpine
    command: postgres -c config_file=/etc/postgresql.conf
    shm_size: '4gb'
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    ports:
      - "7032:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: './api/.env'
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
      retries: 300
    networks:
      - app-network



  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: springboot-dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "35729:35729" # LiveReload port
    volumes:
      - ./api:/app
      - maven-repo:/root/.m2
    networks:
      - app-network



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-dev
    depends_on:
      - backend
    ports:
      - "4200:4200" # Angular dev server port
      - "49153:49153" # Webpack dev server websocket port
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:
  maven-repo:
  node_modules:

networks:
  app-network:
    driver: bridge


#networks:
#  docker-monitoring_public:
#    external: true