import colors from "tailwindcss/colors.js";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.jsx",
    "./resources/**/*.tsx",
    "./resources/**/*.ts",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      BgColor: '#F4F3EE',
      Primary: '#463F3A',
      Secondary: '#8A817C',
      Tertiary: '#BCB8B1',
      Quaternary: '#E0AFA0',
      Error: '#E74C3C',
      Warning: '#F39C12',
      Success: '#4CAF50',
      Extra: '#A3EBF3',
      TextColor: '#1C1B1A',
    },
    fontFamily: {
      'sans': ['Inter', 'sans-serif'],
    },
    extend: {},
  },
  plugins: [],
}