
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CardProjectCard': typeof import("../components/Card/ProjectCard.vue")['default']
    'CheckboxLoginCustomCheckbox': typeof import("../components/Checkbox/LoginCustomCheckbox.vue")['default']
    'IconIssueIcon': typeof import("../components/Icon/IssueIcon.vue")['default']
    'IconPriorityIcon': typeof import("../components/Icon/PriorityIcon.vue")['default']
    'IssueActivityItem': typeof import("../components/Issue/Activity/ActivityItem.vue")['default']
    'IssueActivityCommentCard': typeof import("../components/Issue/Activity/CommentCard.vue")['default']
    'IssueDetailViewIssueCardList': typeof import("../components/Issue/DetailView/IssueCardList.vue")['default']
    'IssueDetailViewIssueDetail': typeof import("../components/Issue/DetailView/IssueDetail.vue")['default']
    'IssueKanbanViewIssueKanban': typeof import("../components/Issue/KanbanView/IssueKanban.vue")['default']
    'IssueKanbanViewIssueKanbanDetails': typeof import("../components/Issue/KanbanView/issueKanbanDetails.vue")['default']
    'IssueListViewDnDIssue': typeof import("../components/Issue/ListView/DnDIssue.vue")['default']
    'IssueListViewIssueDetails': typeof import("../components/Issue/ListView/IssueDetails.vue")['default']
    'IssueListViewIssueList': typeof import("../components/Issue/ListView/IssueList.vue")['default']
    'IssueListViewIssueListDetails': typeof import("../components/Issue/ListView/IssueListDetails.vue")['default']
    'MenuIssueMenu': typeof import("../components/Menu/IssueMenu.vue")['default']
    'MenuProject': typeof import("../components/Menu/MenuProject.vue")['default']
    'ModalsProjectCreateProjectModal': typeof import("../components/Modals/Project/CreateProjectModal.vue")['default']
    'ModalsProjectDeleteProjectModal': typeof import("../components/Modals/Project/DeleteProjectModal.vue")['default']
    'ModalsProjectEditProjectModal': typeof import("../components/Modals/Project/EditProjectModal.vue")['default']
    'ModalsProjectSettingsModal': typeof import("../components/Modals/Project/ProjectSettingsModal.vue")['default']
    'ModalsIssueCreateIssueModal': typeof import("../components/Modals/issue/CreateIssueModal.vue")['default']
    'ModalsIssueDeleteIssueModal': typeof import("../components/Modals/issue/DeleteIssueModal.vue")['default']
    'ModalsIssueEditIssueModal': typeof import("../components/Modals/issue/EditIssueModal.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'ProjectWorkflowSettingsModule': typeof import("../components/Project/Workflow/WorkflowSettingsModule.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCardProjectCard': typeof import("../components/Card/ProjectCard.vue")['default']
    'LazyCheckboxLoginCustomCheckbox': typeof import("../components/Checkbox/LoginCustomCheckbox.vue")['default']
    'LazyIconIssueIcon': typeof import("../components/Icon/IssueIcon.vue")['default']
    'LazyIconPriorityIcon': typeof import("../components/Icon/PriorityIcon.vue")['default']
    'LazyIssueActivityItem': typeof import("../components/Issue/Activity/ActivityItem.vue")['default']
    'LazyIssueActivityCommentCard': typeof import("../components/Issue/Activity/CommentCard.vue")['default']
    'LazyIssueDetailViewIssueCardList': typeof import("../components/Issue/DetailView/IssueCardList.vue")['default']
    'LazyIssueDetailViewIssueDetail': typeof import("../components/Issue/DetailView/IssueDetail.vue")['default']
    'LazyIssueKanbanViewIssueKanban': typeof import("../components/Issue/KanbanView/IssueKanban.vue")['default']
    'LazyIssueKanbanViewIssueKanbanDetails': typeof import("../components/Issue/KanbanView/issueKanbanDetails.vue")['default']
    'LazyIssueListViewDnDIssue': typeof import("../components/Issue/ListView/DnDIssue.vue")['default']
    'LazyIssueListViewIssueDetails': typeof import("../components/Issue/ListView/IssueDetails.vue")['default']
    'LazyIssueListViewIssueList': typeof import("../components/Issue/ListView/IssueList.vue")['default']
    'LazyIssueListViewIssueListDetails': typeof import("../components/Issue/ListView/IssueListDetails.vue")['default']
    'LazyMenuIssueMenu': typeof import("../components/Menu/IssueMenu.vue")['default']
    'LazyMenuProject': typeof import("../components/Menu/MenuProject.vue")['default']
    'LazyModalsProjectCreateProjectModal': typeof import("../components/Modals/Project/CreateProjectModal.vue")['default']
    'LazyModalsProjectDeleteProjectModal': typeof import("../components/Modals/Project/DeleteProjectModal.vue")['default']
    'LazyModalsProjectEditProjectModal': typeof import("../components/Modals/Project/EditProjectModal.vue")['default']
    'LazyModalsProjectSettingsModal': typeof import("../components/Modals/Project/ProjectSettingsModal.vue")['default']
    'LazyModalsIssueCreateIssueModal': typeof import("../components/Modals/issue/CreateIssueModal.vue")['default']
    'LazyModalsIssueDeleteIssueModal': typeof import("../components/Modals/issue/DeleteIssueModal.vue")['default']
    'LazyModalsIssueEditIssueModal': typeof import("../components/Modals/issue/EditIssueModal.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyProjectWorkflowSettingsModule': typeof import("../components/Project/Workflow/WorkflowSettingsModule.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CardProjectCard: typeof import("../components/Card/ProjectCard.vue")['default']
export const CheckboxLoginCustomCheckbox: typeof import("../components/Checkbox/LoginCustomCheckbox.vue")['default']
export const IconIssueIcon: typeof import("../components/Icon/IssueIcon.vue")['default']
export const IconPriorityIcon: typeof import("../components/Icon/PriorityIcon.vue")['default']
export const IssueActivityItem: typeof import("../components/Issue/Activity/ActivityItem.vue")['default']
export const IssueActivityCommentCard: typeof import("../components/Issue/Activity/CommentCard.vue")['default']
export const IssueDetailViewIssueCardList: typeof import("../components/Issue/DetailView/IssueCardList.vue")['default']
export const IssueDetailViewIssueDetail: typeof import("../components/Issue/DetailView/IssueDetail.vue")['default']
export const IssueKanbanViewIssueKanban: typeof import("../components/Issue/KanbanView/IssueKanban.vue")['default']
export const IssueKanbanViewIssueKanbanDetails: typeof import("../components/Issue/KanbanView/issueKanbanDetails.vue")['default']
export const IssueListViewDnDIssue: typeof import("../components/Issue/ListView/DnDIssue.vue")['default']
export const IssueListViewIssueDetails: typeof import("../components/Issue/ListView/IssueDetails.vue")['default']
export const IssueListViewIssueList: typeof import("../components/Issue/ListView/IssueList.vue")['default']
export const IssueListViewIssueListDetails: typeof import("../components/Issue/ListView/IssueListDetails.vue")['default']
export const MenuIssueMenu: typeof import("../components/Menu/IssueMenu.vue")['default']
export const MenuProject: typeof import("../components/Menu/MenuProject.vue")['default']
export const ModalsProjectCreateProjectModal: typeof import("../components/Modals/Project/CreateProjectModal.vue")['default']
export const ModalsProjectDeleteProjectModal: typeof import("../components/Modals/Project/DeleteProjectModal.vue")['default']
export const ModalsProjectEditProjectModal: typeof import("../components/Modals/Project/EditProjectModal.vue")['default']
export const ModalsProjectSettingsModal: typeof import("../components/Modals/Project/ProjectSettingsModal.vue")['default']
export const ModalsIssueCreateIssueModal: typeof import("../components/Modals/issue/CreateIssueModal.vue")['default']
export const ModalsIssueDeleteIssueModal: typeof import("../components/Modals/issue/DeleteIssueModal.vue")['default']
export const ModalsIssueEditIssueModal: typeof import("../components/Modals/issue/EditIssueModal.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const ProjectWorkflowSettingsModule: typeof import("../components/Project/Workflow/WorkflowSettingsModule.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCardProjectCard: typeof import("../components/Card/ProjectCard.vue")['default']
export const LazyCheckboxLoginCustomCheckbox: typeof import("../components/Checkbox/LoginCustomCheckbox.vue")['default']
export const LazyIconIssueIcon: typeof import("../components/Icon/IssueIcon.vue")['default']
export const LazyIconPriorityIcon: typeof import("../components/Icon/PriorityIcon.vue")['default']
export const LazyIssueActivityItem: typeof import("../components/Issue/Activity/ActivityItem.vue")['default']
export const LazyIssueActivityCommentCard: typeof import("../components/Issue/Activity/CommentCard.vue")['default']
export const LazyIssueDetailViewIssueCardList: typeof import("../components/Issue/DetailView/IssueCardList.vue")['default']
export const LazyIssueDetailViewIssueDetail: typeof import("../components/Issue/DetailView/IssueDetail.vue")['default']
export const LazyIssueKanbanViewIssueKanban: typeof import("../components/Issue/KanbanView/IssueKanban.vue")['default']
export const LazyIssueKanbanViewIssueKanbanDetails: typeof import("../components/Issue/KanbanView/issueKanbanDetails.vue")['default']
export const LazyIssueListViewDnDIssue: typeof import("../components/Issue/ListView/DnDIssue.vue")['default']
export const LazyIssueListViewIssueDetails: typeof import("../components/Issue/ListView/IssueDetails.vue")['default']
export const LazyIssueListViewIssueList: typeof import("../components/Issue/ListView/IssueList.vue")['default']
export const LazyIssueListViewIssueListDetails: typeof import("../components/Issue/ListView/IssueListDetails.vue")['default']
export const LazyMenuIssueMenu: typeof import("../components/Menu/IssueMenu.vue")['default']
export const LazyMenuProject: typeof import("../components/Menu/MenuProject.vue")['default']
export const LazyModalsProjectCreateProjectModal: typeof import("../components/Modals/Project/CreateProjectModal.vue")['default']
export const LazyModalsProjectDeleteProjectModal: typeof import("../components/Modals/Project/DeleteProjectModal.vue")['default']
export const LazyModalsProjectEditProjectModal: typeof import("../components/Modals/Project/EditProjectModal.vue")['default']
export const LazyModalsProjectSettingsModal: typeof import("../components/Modals/Project/ProjectSettingsModal.vue")['default']
export const LazyModalsIssueCreateIssueModal: typeof import("../components/Modals/issue/CreateIssueModal.vue")['default']
export const LazyModalsIssueDeleteIssueModal: typeof import("../components/Modals/issue/DeleteIssueModal.vue")['default']
export const LazyModalsIssueEditIssueModal: typeof import("../components/Modals/issue/EditIssueModal.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyProjectWorkflowSettingsModule: typeof import("../components/Project/Workflow/WorkflowSettingsModule.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
