name: tempestboard-cd

on:
  workflow_run:
    workflows:
      - tempestboard-ci
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:

    permissions:
      packages: read
      actions: read

    name: deploy
    runs-on: self-hosted
    steps:
      - name: setup-shh
        run: |
          which ssh-agent || (sudo apk update && sudo apk add openssh-client)
          which rsync || (sudo apk update && sudo apk add rsync)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/github-actions.key
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/github-actions.key
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github-actions.key
          # Append keyscan output into known hosts
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/github-actions.key
          cat >>~/.ssh/config <<END
          Host vps
            HostName ${{ secrets.SSH_HOST }}
            Port ${{ secrets.SSH_PORT }}
            User debian
            IdentityFile ~/.ssh/github-actions.key
            StrictHostKeyChecking no
          END
      - name: get-artifact-front
        uses: actions/download-artifact@v4
        with:
          name: tempestboard-artifact-front
          path: front
          run-id: '${{ github.event.workflow_run.id }}'
      - name: upload-artifact-front
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/github-actions.key
          rsync --delete -avz front/ vps:/tmp/front